# Generated by Django 6.1 on 2026-08-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyroom',
            name='current_timer_status',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
